"use client";

import { useCallback } from "react";
import { useThemeAndLocale } from "@/components/ThemeAndLocaleProvider";

const COPY_KEYS: Record<string, string> = {
  "信息修改申请": "admin.pages.correctionsTitle",
  "身份认证审核": "admin.pages.identityTitle",
  "身份申请与审核记录": "admin.pages.identityDescription",
  "内容审核": "admin.pages.postsTitle",
  "审核校友故事、母港动态与招聘信息等投稿内容": "admin.pages.postsDescription",
  "校友名单": "admin.pages.alumniTitle",
  "新闻管理": "admin.pages.newsTitle",
  "发布、编辑并运营母港新闻与公告记录": "admin.pages.newsDescription",
  "活动管理": "admin.pages.eventsTitle",
  "创建、发布并运营校友活动记录": "admin.pages.eventsDescription",
  "待审核故事": "admin.pages.pendingStoriesTitle",
  "审核前台校友提交的故事投稿——通过或驳回": "admin.pages.pendingStoriesDescription",
  "编辑新闻": "admin.pages.editNewsTitle",
  "修改新闻标题、正文与发布状态": "admin.pages.editNewsDescription",
  "发布新闻": "admin.pages.publishNewsTitle",
  "发布新闻动态或公告": "admin.pages.publishNewsDescription",
  "创建活动": "admin.pages.createEventTitle",
  "发布新的校友活动，设定地点、时间与人数限制": "admin.pages.createEventDescription",
  "编辑活动": "admin.pages.editEventTitle",
  "修改活动基本信息、状态与名额限制": "admin.pages.editEventDescription",
  "报名名单": "admin.pages.registrationsTitle",
  "活动报名记录": "admin.pages.registrationsDescription",
  "校友成就墙管理": "admin.pages.achievementsTitle",
  "新增、编辑并发布校友成就记录": "admin.pages.achievementsDescription",
  "燕中故事管理": "admin.pages.storiesTitle",
  "管理校友故事投稿——增删改查": "admin.pages.storiesDescription",
};

const EN_COPY: Record<string, string> = {
  "标题": "Title",
  "正文": "Content",
  "作者": "Author",
  "日期": "Date",
  "届别": "Graduation Cohort",
  "班级": "Class",
  "姓名": "Name",
  "邮箱": "Email",
  "联系方式": "Contact Details",
  "城市": "City",
  "院校": "University",
  "专业": "Major",
  "行业": "Industry",
  "排序": "Sort Order",
  "类别": "Category",
  "年份": "Year",
  "发布状态": "Publication Status",
  "草稿": "Draft",
  "已发布": "Published",
  "审核中": "In Review",
  "已通过": "Approved",
  "已驳回": "Rejected",
  "待审核": "Pending Review",
  "已结束": "Ended",
  "报名中": "Registration Open",
  "校友姓名": "Alumni Name",
  "成就标题": "Achievement Title",
  "机构或单位": "Organization",
  "成就简介": "Achievement Summary",
  "升学深造": "Further Education",
  "科研创新": "Research & Innovation",
  "职业发展": "Career Development",
  "创业实践": "Entrepreneurship",
  "公益服务": "Public Service",
  "其他成就": "Other Achievement",
  "标签（逗号分隔）": "Tags (comma-separated)",
  "标签": "Tags",
  "封面图": "Cover Image",
  "图片地址": "Image URL",
  "地点": "Location",
  "开始时间": "Start Time",
  "结束时间": "End Time",
  "人数上限": "Capacity",
  "摘要": "Summary",
  "描述": "Description",
  "说明": "Description",
  "备注": "Notes",
  "图标": "Icon",
  "链接": "Link",
  "按钮文字": "Action Label",
  "新增": "Add",
  "保存": "Save",
  "取消": "Cancel",
  "编辑": "Edit",
  "删除": "Delete",
  "操作": "Actions",
  "删除成功": "Deleted successfully.",
  "重试": "Retry",
  "导入": "Import",
  "导出": "Export",
  "搜索": "Search",
  "上一页": "Previous",
  "下一页": "Next",
  "关闭": "Close",
  "确认删除": "Confirm Deletion",
  "暂无简介": "No summary provided",
  "暂无数据": "No data yet",
  "例：2025": "Example: 2025",
  "例：2026": "Example: 2026",
  "学校、单位或组织名称": "School, company, or organization",
  "专业真相, 避坑指南": "Inside the Major, Practical Guide",
  "确定删除这个故事？": "Delete this story?",
  "确定删除这条成就记录？": "Delete this achievement?",
  "标题和正文不能为空": "A title and content are required.",
  "校友姓名和成就标题不能为空": "Alumni name and achievement title are required.",
  "标题不能为空": "A title is required.",
  "确定删除？": "Delete this item?",
  "确定删除这个版块？": "Delete this section?",
  "确定删除这条记忆？": "Delete this memory item?",
  "页面内容管理": "Page Content",
  "管理各页面的版块内容与排序": "Manage page sections and display order.",
  "教师频道管理": "Teachers Channel",
  "管理教师频道页面的版块内容和排序": "Manage Teachers Channel sections and display order.",
  "燕中记忆管理": "School Memories",
  "管理文化长廊展示的校园记忆展品": "Manage memory items shown in the school archive.",
  "学校介绍 - 特色卡片": "About School - Features",
  "学校介绍 - 发展历程": "About School - Timeline",
  "联系我们": "Contact Us",
  "在校生资源站": "Student Resources",
  "教师频道": "Teachers Channel",
  "书本": "Book",
  "明星": "Star",
  "爱心": "Heart",
  "消息": "Message",
  "学位帽": "Graduation Cap",
  "用户群": "Users",
  "学校": "School",
  "建筑": "Building",
  "地球": "Globe",
  "地图": "Map",
  "火箭": "Rocket",
  "历史": "History",
  "编辑内容": "Edit Content",
  "新增内容": "Add Content",
  "编辑版块": "Edit Section",
  "新增版块": "Add Section",
  "编辑记忆展品": "Edit Memory Item",
  "新增记忆展品": "Add Memory Item",
  "保存中...": "Saving...",
  "更新": "Update",
  "取消编辑": "Cancel Editing",
  "加载中...": "Loading...",
  "暂无内容，使用上方表单新增。": "No content yet. Use the form above to add a section.",
  "暂无版块，使用上方表单新增。": "No sections yet. Use the form above to add one.",
  "暂无记忆展品，使用上方表单新增。": "No memory items yet. Use the form above to add one.",
  "底部备注": "Footer Note",
  "跳转链接（可选）": "Destination Link (optional)",
  "按钮文字（可选）": "Action Label (optional)",
  "如：2022": "Example: 2022",
  "如：教师名录": "Example: Teacher Directory",
  "版块描述文字...": "Describe this section...",
  "如：教师信息收集整理中，欢迎校友提供资料": "Example: Teacher information is being collected; alumni contributions are welcome.",
  "如：/alumni/stories": "Example: /alumni/stories",
  "如：通过燕中故事投稿表达": "Example: Submit through Yan-Zhong Stories",
  "含链接": "Linked",
  "无描述": "No description",
  "上移": "Move Up",
  "下移": "Move Down",
  "相机（默认）": "Camera (default)",
  "校门": "School Gate",
  "教学楼": "Teaching Building",
  "图书馆": "Library",
  "操场": "Sports Field",
  "林荫道": "Tree-lined Walk",
  "副标题": "Subtitle",
  "上传图片路径": "Image Path",
  "本地上传": "Upload File",
  "上传中...": "Uploading...",
  "上传失败": "Upload failed.",
  "图片说明（alt）": "Image Description (alt)",
  "如：校门与晨曦": "Example: School Gate at Dawn",
  "如：入学第一张照片": "Example: First Photo at School",
  "展品描述文字...": "Describe this memory item...",
  "/uploads/xxx.jpg 或上传": "/uploads/xxx.jpg or upload a file",
  "图片文字描述": "Describe the image",
  "无副标题": "No subtitle",
  "未设置": "Not set",
  "图片": "Image",
  "加载数据失败": "Failed to load data.",
  "操作失败": "The operation failed.",
  "数据加载中...": "Loading data...",
  "届别未填": "Cohort not provided",
  "无联系方式": "No contact details",
  "未命名": "Unnamed",
  "无说明": "No description",
  "管理员备注说明": "Administrator Notes",
  "可在此输入管理员备注说明": "Add administrator notes",
  "请求失败": "Request failed.",
  "加载失败": "Failed to load.",
  "审核操作失败": "Review action failed.",
  "全部": "All",
  "毕业校友": "Alumni",
  "在校生": "Current Student",
  "教师": "Teacher",
  "名单唯一匹配": "Unique Roster Match",
  "存在同名冲突": "Name Conflict",
  "名单未匹配": "No Roster Match",
  "无需名单匹配": "Roster Match Not Required",
  "正在加载": "Loading...",
  "暂无身份认证申请": "No identity verification requests",
  "当前筛选条件下没有记录": "No records match the current filter.",
  "微信用户": "WeChat User",
  "提交于": "Submitted",
  "毕业或预计毕业年份": "Graduation or Expected Graduation Year",
  "教师职位": "Teacher Position",
  "当前角色": "Current Role",
  "审核备注（选填）": "Review Notes (optional)",
  "处理中": "Processing...",
  "通过": "Approve",
  "驳回": "Reject",
  "管理员": "Administrator",
  "共": "Total",
  "条": "records",
  "获取待审核故事失败": "Failed to load pending stories.",
  "暂无待审核的故事投稿": "No stories awaiting review",
  "署名作者": "Byline",
  "提交时间": "Submitted",
  "故事发生日期": "Story Date",
  "投稿账号关联信息": "Submitting Account",
  "用户名": "Username",
  "未填写": "Not provided",
  "通过 (Approve)": "Approve",
  "驳回 (Reject)": "Reject",
  "搜索姓名、联系方式": "Search by name or contact details",
  "搜索姓名、联系方式...": "Search by name or contact details...",
  "未找到匹配的申请": "No matching requests",
  "暂无修改申请": "No correction requests",
  "校友数据更新后将在此处统一管理与审核": "Alumni record corrections are reviewed and managed here.",
  "状态": "Status",
  "收起详情": "Collapse Details",
  "展开详情": "Expand Details",
  "未知": "Unknown",
  "正在加载修改申请...": "Loading correction requests...",
  "（不修改）": "No change",
  "修改说明": "Reason for Correction",
  "管理员备注": "Administrator Note",
  "通过并应用": "Approve and Apply",
  "驳回申请": "Reject Request",
  "修改内容": "Requested Changes",
  "申请信息": "Request Details",
  "通过并应用修改": "Approve and Apply Changes",
  "管理员备注（可选）": "Administrator Note (optional)",
  "可选：记录审核备注": "Optional: add review notes",
  "可选：记录驳回原因": "Optional: explain the rejection",
  "确认通过": "Confirm Approval",
  "确认驳回": "Confirm Rejection",
  "申请已批准，名单已自动更新": "Request approved and the roster was updated.",
  "申请已驳回": "Request rejected.",
  "发布新闻": "Publish News",
  "搜索新闻标题": "Search news titles",
  "搜索新闻标题...": "Search news titles...",
  "当前筛选": "Current filter",
  "显示": "Showing",
  "更新时间": "Updated",
  "未找到匹配的新闻": "No matching news",
  "暂无新闻记录": "No news items",
  "点击右上角“发布新闻”来新增第一条记录": "Use Publish News to add the first item.",
  "新闻已删除": "News item deleted.",
  "删除失败": "Deletion failed.",
  "删除中...": "Deleting...",
  "创建活动": "Create Event",
  "搜索活动标题或地点": "Search event title or location",
  "搜索标题或地点...": "Search title or location...",
  "活动时间": "Event Time",
  "报名": "Registrations",
  "暂无活动记录": "No event records",
  "点击右上角“创建活动”来新增第一条记录": "Use Create Event to add the first event.",
  "未找到匹配的活动": "No matching events",
  "可以尝试调整您的搜索关键词": "Try a different search term.",
  "活动已删除": "Event deleted.",
  "待审": "In Review",
  "校友故事": "Alumni Story",
  "母港动态": "Alumni Port Update",
  "招聘信息": "Job Posting",
  "类型": "Type",
  "发布": "Publish",
  "下架": "Unpublish",
  "重新发布": "Republish",
  "状态更新成功": "Status updated.",
  "更新状态失败": "Failed to update status.",
  "获取内容列表失败": "Failed to load content.",
  "暂无匹配的内容记录": "No matching content",
  "校友投稿审核处理完毕后将在此归档显示": "Reviewed submissions are archived here.",
  "未知作者": "Unknown Author",
  "返回列表": "Back to List",
  "新闻标题": "News Title",
  "新闻摘要（可选）": "News summary (optional)",
  "新闻正文（支持换行）": "News content (line breaks supported)",
  "封面图片": "Cover Image",
  "选择图片": "Choose Image",
  "封面预览": "Cover Preview",
  "提交中...": "Submitting...",
  "创建失败": "Creation failed.",
  "新闻发布成功": "News item published.",
  "发布失败": "Publishing failed.",
  "获取新闻失败": "Failed to load the news item.",
  "更新失败": "Update failed.",
  "新闻已更新": "News item updated.",
  "移除封面": "Remove Cover",
  "保存修改": "Save Changes",
  "活动标题": "Event Title",
  "活动摘要（可选）": "Event summary (optional)",
  "活动详情（支持换行）": "Event details (line breaks supported)",
  "报名人数上限": "Registration Capacity",
  "活动地点": "Event location",
  "留空表示不限制": "Leave blank for no limit",
  "活动创建成功": "Event created.",
  "选择CSV文件导入校友": "Choose a CSV file to import alumni",
  "搜索校友...": "Search alumni...",
  "搜索校友": "Search alumni",
  "按届别筛选": "Filter by Cohort",
  "未找到匹配的校友": "No matching alumni",
  "暂无校友数据": "No alumni records",
  "新增第一条校友": "Add the First Alumni Record",
  "添加时间": "Added",
  "关闭导入结果": "Close import results",
  "编辑校友": "Edit Alumni",
  "新增校友": "Add Alumni",
  "关闭表单": "Close form",
  "请输入姓名": "Enter a name",
  "例如：2025": "Example: 2025",
  "例如：1": "Example: 1",
  "用于区分同名同届校友": "Used to distinguish alumni with the same name and cohort",
  "手机号或微信": "Phone number or WeChat ID",
  "例如：深圳": "Example: Shenzhen",
  "例如：北京大学": "Example: Peking University",
  "例如：计算机科学": "Example: Computer Science",
  "例如：互联网": "Example: Technology",
  "证书编号": "Certificate Number",
  "可选，如 YC-2022-001": "Optional, for example YC-2022-001",
  "留空则自动使用系统 ID": "Leave blank to use the system ID.",
  "保存失败": "Save failed.",
  "修改成功": "Changes saved.",
  "新增成功": "Record added.",
  "导入失败，请检查数据格式": "Import failed. Check the data format.",
  "导入请求失败": "Import request failed.",
  "姓名不能为空且不超过50字": "Name is required and must be 50 characters or fewer.",
  "届别需为2025起的四位年份数字": "Cohort must be a four-digit year from 2025 onward.",
  "班级需为1-99的数字": "Class must be a number from 1 to 99.",
  "邮箱格式无效": "Enter a valid email address.",
  "联系方式需为11位手机号": "Contact number must be an 11-digit mobile number.",
  "获取活动失败": "Failed to load the event.",
  "更新成功": "Updated successfully.",
  "当前报名人数": "Current Registrations",
  "人": "people",
  "不限": "No limit",
  "查看报名名单": "View Registrations",
  "获取报名列表失败": "Failed to load registrations.",
  "导出报名名单失败": "Failed to export registrations.",
  "报名名单已导出": "Registration list exported.",
  "导出中": "Exporting...",
  "导出 CSV": "Export CSV",
  "返回编辑": "Back to Event",
  "有效报名": "Active Registrations",
  "全部记录": "All Records",
  "暂无报名记录": "No registrations yet",
  "该活动目前还没有校友登记报名": "No alumni have registered for this event.",
  "有效": "Active",
  "未通过": "Not Approved",
  "已取消": "Cancelled",
  "留言": "Message",
  "报名时间": "Registered",
};

export function useAdminLocalize() {
  const { locale, t } = useThemeAndLocale();

  return useCallback((value?: string | null) => {
    if (!value || locale === "zh") return value || "";
    const key = COPY_KEYS[value];
    if (key) return t(key);
    if (EN_COPY[value]) return EN_COPY[value];

    const countMatch = value.match(/^共 (\d+) 条(申请|记录)$/);
    if (countMatch) return `Total ${countMatch[1]} ${countMatch[2] === "申请" ? "requests" : "records"}`;
    const eventMatch = value.match(/^活动《(.+)》的报名记录$/);
    if (eventMatch) return `Registrations for “${eventMatch[1]}”`;
    return value;
  }, [locale, t]);
}

export function AdminLocalizedText({ children }: { children: string }) {
  const localize = useAdminLocalize();
  return <>{localize(children)}</>;
}
